PR for breadcrumbs
ndorfin/vanilla-web-assets pull request #4
Opened 2024-07-15 10:03 UTC by yehudahsilberg

2024-07-16 05:28 UTC, ndorfin requested changes
I like the simpleness of the `display: inline` strategy here. Good stuff.

2024-07-16 05:28 UTC, ndorfin commented on src/css/patterns/breadcrumb.css
> +	list-style-type: none;
For this to be correctly read out as a list, you need to use `list-style-type: '';` rather than `none`

2024-07-16 05:28 UTC, ndorfin commented on src/css/patterns/breadcrumb.css
> +	display: inline;
This is quite elegant, nice!

2024-07-16 05:28 UTC, ndorfin commented on src/css/patterns/breadcrumb.css
> +	color: var(--container-color-link);
I'm not sure it's a good idea to use this specific variable. We can't be sure this element will be placed within a `container`. Instead, use a general colour here.

2024-07-16 05:28 UTC, ndorfin commented on src/css/patterns/breadcrumb.css
> +.breadcrumb > li > a:hover {
We might adjust this behaviour for all links later, but for now, this is fine.

2024-07-16 05:28 UTC, ndorfin commented on src/css/patterns/breadcrumb.css
> +.breadcrumb > li > *:not(a) {
This rule will be mostly defunct once you make the HTML changes in the PL PR.

You could also treat the list-item as the default color holder, as any `color` properties will be inherited. Then set an alternate colour on anchors.

(In other words, set the default colour of list-items to this line's desired colour, and set a different colour for all links in this component)

2024-07-16 10:17 UTC, yehudahsilberg commented on src/css/patterns/breadcrumb.css
> +	display: inline;
Thank you

2024-07-17 05:34 UTC, ndorfin approved these changes
This looks great. Happy for your to merge it after the desired HTML changes have been approved too.

2024-07-17 07:45 UTC, merged